version: 2.1

jobs:
  unit_test:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run Unit Tests with Maven
          command: mvn clean test

  integration_test:
    docker:
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
          name: Setup Database
          command: |
            mysql -u root -e "CREATE DATABASE test_db;"
      - run:
          name: Run Integration Tests
          command: mvn clean verify -Pintegration-test

  functional_test:
    docker:
      - image: selenium/standalone-chrome:latest
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Run Selenium Functional Tests
          command: mvn clean verify -Pfunctional-test

  deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: ./deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit_test
      - integration_test:
          requires:
            - unit_test
      - functional_test:
          requires:
            - integration_test
      - deploy:
          requires:
            - functional_test
          filters:
            branches:
              only: main
